apiVersion: v1
kind: PersistentVolume
metadata:
  name: radar-backend-logs-pv
  labels:
    app: radar-backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/eurotec/radar/backend/logs
    type: DirectoryOrCreate
